### ISSUE TITLE
Object - Graph - Object Mappings

### ISSUE THREAD

**Issue by simontaurus** [OO-LD/schema#10]
> Data
```yml
'@context':
  schema: 'http://schema.org/'
  works_for:
    '@id': 'schema:worksFor'
    '@type': '@id'
  name: 'schema:name'
  type: '@type'
  id: '@id'
  demo: 'https://oo-ld.github.io/demo/'
'@graph':
  - id: 'demo:person1'
    type: 'schema:Person'
    name: Person1
    works_for:
      - 'demo:organizationA'
      - 'demo:organizationB'
  - id: 'demo:organizationA'
    type: 'schema:Organization'
  - id: 'demo:organizationB'
    type: 'schema:Organization'
```

> Frame
```yml
'@context':
  schema: 'http://schema.org/'
  employes:
    '@reverse': 'schema:worksFor'
    '@type': '@id'
  name: 'schema:name'
  type: '@type'
  id: '@id'
  demo: 'https://oo-ld.github.io/demo/'
type: 'schema:Organization'
employes:
  type: 'schema:Person'
  name: {}
  '@explicit': true

```

> Result
```yml
'@context':
  schema: 'http://schema.org/'
  employes:
    '@reverse': 'schema:worksFor'
    '@type': '@id'
  name: 'schema:name'
  type: '@type'
  id: '@id'
  demo: 'https://oo-ld.github.io/demo/'
'@graph':
  - id: 'demo:organizationA'
    employes:
      id: 'demo:person1'
      type: 'schema:Person'
      name: Person1
    type: 'schema:Organization'
  - id: 'demo:organizationB'
    employes:
      id: 'demo:person1'
      type: 'schema:Person'
      name: Person1
    type: 'schema:Organization'

```

[playground](https://json-ld.org/playground/#startTab=tab-framed&json-ld=%7B%22%40context%22%3A%7B%22schema%22%3A%22http%3A%2F%2Fschema.org%2F%22%2C%22works_for%22%3A%7B%22%40id%22%3A%22schema%3AworksFor%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22name%22%3A%22schema%3Aname%22%2C%22type%22%3A%22%40type%22%2C%22id%22%3A%22%40id%22%2C%22demo%22%3A%22https%3A%2F%2Foo-ld.github.io%2Fdemo%2F%22%7D%2C%22%40graph%22%3A%5B%7B%22id%22%3A%22demo%3Aperson1%22%2C%22type%22%3A%22schema%3APerson%22%2C%22name%22%3A%22Person1%22%2C%22works_for%22%3A%5B%22demo%3AorganizationA%22%2C%22demo%3AorganizationB%22%5D%7D%2C%7B%22id%22%3A%22demo%3AorganizationA%22%2C%22type%22%3A%22schema%3AOrganization%22%7D%2C%7B%22id%22%3A%22demo%3AorganizationB%22%2C%22type%22%3A%22schema%3AOrganization%22%7D%5D%7D&frame=%7B%22%40context%22%3A%7B%22schema%22%3A%22http%3A%2F%2Fschema.org%2F%22%2C%22employes%22%3A%7B%22%40reverse%22%3A%22schema%3AworksFor%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22name%22%3A%22schema%3Aname%22%2C%22type%22%3A%22%40type%22%2C%22id%22%3A%22%40id%22%2C%22demo%22%3A%22https%3A%2F%2Foo-ld.github.io%2Fdemo%2F%22%7D%2C%22type%22%3A%22schema%3AOrganization%22%2C%22employes%22%3A%7B%22type%22%3A%22schema%3APerson%22%2C%22name%22%3A%7B%7D%2C%22%40explicit%22%3Atrue%7D%7D)
