### ISSUE TITLE
JSON-SCHEMA for DLite data models

### ISSUE THREAD

**Issue by jesper-friis** [OO-LD/schema#17]
The intension with this issue is to discuss the excellent suggestion in the README file for a JSON-SCHEMA for DLite data models: https://github.com/OO-LD/schema/blob/main/README.md#dlite

# DLite datamodel representation
The suggestion in the [README file](https://github.com/OO-LD/schema/blob/main/README.md#dlite) is based on the [soft7](https://sintef.github.io/dlite/user_guide/datamodels.html#the-soft5-and-soft7-formats) json structure for DLite datamodels. 
However, the [soft5](https://sintef.github.io/dlite/user_guide/datamodels.html#the-soft5-and-soft7-formats) format may be better suited for our purpose?

# Property dimensionality
An alternative to the common dimensions used in DLite to express the dimensionality of the properties, is to define a set of *coordinate systems* on which the properties are defined. The benefit of this is that a property could be defined as a subclass of the class of quantities defined on a given space (or alternatively with a defined-on-a-given-space restriction). However, it also requires that we define a set of additional classes representing the needed spaces and quantity classes.

A coordinate system is defined as a set of ordered axes (or dimensions) where each axis is represented by a quantity (think EMMO quantity, which could be an ISQ dimensionless quantity). 

> 🔰 **Example**
> Consider a property `temperature`, which is the temperature measured at different sea depths at different times. Hence, it has as domain a coordinate system with two axis; *depth* and *time*.

As an extension to DLite dimensions, it would be very useful to be able to relate the axes to other properties that defines their values. Continuing the example above, it would be very useful to relate the *depth* axis to a property `depth` (who's domain is coordinate system with *depth* as the only axis) that defines the sea depths at which the temperature measurements are done. Similarly, can the *time* axis be related to a `time` property.

A next step, which would be very useful for interoperability, is to provide a formalisation of transformations between coordinate systems. A coordinate system spans a *space*. Different coordinate systems that spans the same space can be transformed into each other. It is also possible to slice a space or coordinate system.

**Comment by simontaurus** [comment]
@jesper-friis 

Many thanks for providing feedback

Regarding soft5 vs soft7: is having the properties defined as dict with the name as key (soft7) vs. defined as array with the name within the property definition (soft5) the main difference? In this case soft7 is closer to the JSON-SCHEMA property notation

Regarding the example:
Let's see how it would look like in the different schema notations 

dlite - I need your help here!

```yaml
description: A depth-resolved temperature measurement over time - 3-dimensional data
dimensions:
  depth_samples: Number of depth values per point in time
  time_samples: Number of repeated measurements at different points in time
properties:
  data:
    type: [float32, float32, float32]
    unit: [s, m, K]
    shape: [time_samples, depth_samples, 1]
    description: 3-dimensional data
```
> dlite schema 1

Time | Depth | Temperature
------|--------|----------------
0 | 0 | 305
0 | 100 | 299
0 | 200 | 296
3600 | 0 | 303
3600 | 100 | 297
3600 | 200 | 294
> dlite data 1

```yaml
description: A depth-resolved temperature measurement over time - single axes?
dimensions:
  depth_samples: Number of depth values per point in time
  time_samples: Number of repeated measurements at different points in time
properties:
  time:
    type: float32
    unit: s
    shape: [time_samples]
    description: timestamp of the measurement
  depth:
    type: float32
    unit: m
    shape: [time_samples * depth_samples]
    description: depth of the measurement
  temperature:
    type: float32
    unit: K
    shape: [time_samples * depth_samples * 1]
    description: depth of the measurement
```
> dlite schema 2

Time = [0, 3600] s
Depth = [0, 100, 200] m
Temperature = [305, 299, 296, 303, 297, 294] K
> dlite data 2

in OO-LD we would create explicite classes for paired axes:

```yml
title: DepthResolvedTemperature
properties:
  depth:
    type: number
  temperature:
    type: number
```

```yml
title: TimeDepthResolvedTemperature
properties:
  time:
    type: number
  depth:
    type: number
  temperature:
    type: number
```

```yml
title: SeriesOfTimeDepthResolvedTemperature
properties:
  data:
    type: array
    items:
      $ref: ./TimeDepthResolvedTemperature
```
> OO-LD schema 1

```yml
data:
  - {time: 0, depth: 0, temperature: 305}
  - {time: 0, depth: 100, temperature: 299}
  - {time: 0, depth: 200, temperature: 296}
  - {time: 3600, depth: 0, temperature: 303}
  - {time: 3600, depth: 100, temperature: 297}
  - {time: 3600, depth: 200, temperature: 294}
```

or, more accurately if there's only a single timestamp for a depth profile

```yml
title: TimeResolvedSeriesOfDepthResolvedTemperature
properties:
  time:
    type: number
  data:
    type: array
    items:
      $ref: ./DepthResolvedTemperature
```
> OO-LD schema 2

```yml
data:
  - time: 0
    data: 
      - {depth: 0, temperature: 305}
      - {depth: 100, temperature: 299}
      - {depth: 200, temperature: 296}
  - time: 3600
     data: 
       - {depth: 0, temperature: 303}
       - {depth: 100, temperature: 297}
       - {depth: 200, temperature: 294}
```
> OO-LD schema 2

**Comment by jesper-friis** [comment]
> Regarding soft5 vs soft7: is having the properties defined as dict with the name as key (soft7) vs. defined as array with the name within the property definition (soft5) the main difference? 

Yes, that is the main difference.

> In this case soft7 is closer to the JSON-SCHEMA property notation

I see, then we use soft7 notation. For JSON-LD, I think it is opposite. There we don't want to put values in the keys.

> Regarding the example: Let's see how it would look like in the different schema notations

In DLite a property can only have one unit (think of them as physical quantities). 
I think we have two options: 
1. That the times/depths of each temperature measurement are not regular distributed. Then the data must be a 1D array of (time, depth, temperature) values (schema 1).
2. That the times/depths of each temperature measurement are regular distributed. Then the temperature can be a 2D array (schema 2).

DLite datamodels for schema 1:

```yaml
uri: http://onto-ns.com/meta/oold/ex/schema1/TimeDepthTemperatureTriplet
description: A single temperature measurement at a given time and depth.
properties:
  time: 
    type: float32
    unit: emmo:Second
    description: The time of the measurement.
  depth:
    type: float32
    shape: [ndepths]
    unit: emmo:Metre
    description: The depth of the measurement.
  temperature:
    type: float32
    unit: emmo:Kelvin
    description: The measured temperature.
```

```yaml
uri: http://onto-ns.com/meta/oold/ex/schema1/TemperatureMeasurements
description: A sequence of temperature measurements as a function of time and depth.
dimensions:
  nmeasurements: Number of measurements.
properties:
  data: 
    type: ref
    @ref: http://onto-ns.com/meta/oold/ex/schema1/TimeDepthTemperatureTriplet
    shape: [nmeasurements]
    description: Measured temperatures as a function of time and depth.
```

DLite datamodel for schema 2 (essentially the same a you suggested above):

```yaml
uri: http://onto-ns.com/meta/oold/ex/schema1/TemperatureMeasurements
description: Temperature measurements in a time/depth grid.
dimensions:
  time_samples: Number of times at which the temperature measurements are performed.
  depth_samples: Number of depths at which the temperature measurements are performed.
properties:
  temperature:
    type: float32
    shape: [ntimes, ndepths]
    unit: emmo:Kelvin
    description: The measured temperature at each time and depth.
  time: 
    type: float32
    shape: [ntimes]
    unit: emmo:Second
    description: The time at which each measurement is done.
  depth:
    type: float32
    shape: [ndepths]
    unit: emmo:Metre
    description: The depth at which each measurement is done.
```

**Comment by jesper-friis** [comment]
I think that the above shows a quite clear way to transform between OO-LD and DLite.

One question. How should we preserve the unit with OO-LD? By introducing the custum keyword `x-dlite-unit` as suggested in the [schema/README](https://github.com/OO-LD/schema/blob/main/README.md#dlite) file?

```yaml
title: TimeDepthResolvedTemperature
properties:
  time:
    type: number
    x-dlite-unit: s
  depth:
    type: number
    x-dlite-unit: m
  temperature:
    type: number
    x-dlite-unit: K
```

```yaml
title: SeriesOfTimeDepthResolvedTemperature
properties:
  data:
    type: array
    items:
      $ref: ./TimeDepthResolvedTemperature
```
